<a href="https://colab.research.google.com/github/Nievii/deep-learning-challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [4]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [5]:
# Show the new df with the removed columns
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [6]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
vc = application_df['CLASSIFICATION'].value_counts()
print(vc[vc > 1])

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [11]:
# List of classifications to be replaced
print(vc[vc <= 1].index)

Index(['C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150'],
      dtype='object')

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = ['C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150']

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
Other       26
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C1267        2
C1256        2
C1234        2
C1246        2
C3200        2
Name: CLASSIFICATION, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [14]:
# Split our preprocessed data into our features and target arrays
y = application_dummies['IS_SUCCESSFUL'].values
X = application_dummies.drop(columns='IS_SUCCESSFUL').values
print(y)



# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

[1 1 0 ... 0 1 0]

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 672

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 723 (2.82 KB)
Trainable params: 723 (2.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [25]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5324
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6910 - accuracy: 0.5324
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6900 - accuracy: 0.5324
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6839 - accuracy: 0.5324
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6642 - accuracy: 0.5582
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6334 - accuracy: 0.7303
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6076 - accuracy: 0.7310
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5927 - accuracy: 0.7304
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5853 - accuracy: 0.7316
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5827 - accuracy: 0.7313
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5818 - accuracy: 0.7311
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5816 - accuracy: 0.7310
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5814 - accuracy: 0.7312
Epoch 15/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5806 - accuracy: 0.7322
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5810 - accuracy: 0.7315
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5805 - accuracy: 0.7321
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5806 - accuracy: 0.7320
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5821 - accuracy: 0.7303
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5802 - accuracy: 0.7329
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5821 - accuracy: 0.7301
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5807 - accuracy: 0.7316
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5805 - accuracy: 0.7316
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5808 - accuracy: 0.7312
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5799 - accuracy: 0.7324
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5795 - accuracy: 0.7327
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5787 - accuracy: 0.7337
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5790 - accuracy: 0.7330
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5788 - accuracy: 0.7328
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5786 - accuracy: 0.7332
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5791 - accuracy: 0.7329
Epoch 32/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5784 - accuracy: 0.7332
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5784 - accuracy: 0.7330
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5779 - accuracy: 0.7333
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5789 - accuracy: 0.7325
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5789 - accuracy: 0.7325
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5782 - accuracy: 0.7339
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5786 - accuracy: 0.7327
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5810 - accuracy: 0.7296
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5784 - accuracy: 0.7332
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5784 - accuracy: 0.7317
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5784 - accuracy: 0.7324
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5774 - accuracy: 0.7331
Epoch 44/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5780 - accuracy: 0.7318
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5773 - accuracy: 0.7331
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5770 - accuracy: 0.7332
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5770 - accuracy: 0.7324
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5765 - accuracy: 0.7336
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5773 - accuracy: 0.7317
Epoch 50/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5766 - accuracy: 0.7330
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5770 - accuracy: 0.7321
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5763 - accuracy: 0.7324
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5766 - accuracy: 0.7315
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5760 - accuracy: 0.7324
Epoch 55/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5755 - accuracy: 0.7320
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5758 - accuracy: 0.7318
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5757 - accuracy: 0.7320
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5754 - accuracy: 0.7314
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5753 - accuracy: 0.7322
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5754 - accuracy: 0.7322
Epoch 61/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5749 - accuracy: 0.7328
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5751 - accuracy: 0.7328
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5745 - accuracy: 0.7331
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5747 - accuracy: 0.7327
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5744 - accuracy: 0.7323
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5747 - accuracy: 0.7322
Epoch 67/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5748 - accuracy: 0.7329
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5740 - accuracy: 0.7335
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5744 - accuracy: 0.7330
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5738 - accuracy: 0.7331
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5737 - accuracy: 0.7329
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5741 - accuracy: 0.7327
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5739 - accuracy: 0.7330
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5739 - accuracy: 0.7330
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5738 - accuracy: 0.7336
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5736 - accuracy: 0.7325
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5734 - accuracy: 0.7340
Epoch 78/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5742 - accuracy: 0.7311
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5734 - accuracy: 0.7332
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5737 - accuracy: 0.7331
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5737 - accuracy: 0.7330
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5737 - accuracy: 0.7316
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5736 - accuracy: 0.7324
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5731 - accuracy: 0.7328
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5732 - accuracy: 0.7326
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5728 - accuracy: 0.7326
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5729 - accuracy: 0.7323
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5727 - accuracy: 0.7331
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5728 - accuracy: 0.7327
Epoch 90/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5725 - accuracy: 0.7331
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5724 - accuracy: 0.7327
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5716 - accuracy: 0.7328
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5709 - accuracy: 0.7342
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5709 - accuracy: 0.7325
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5703 - accuracy: 0.7331
Epoch 96/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5695 - accuracy: 0.7324
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5694 - accuracy: 0.7333
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5691 - accuracy: 0.7333
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5691 - accuracy: 0.7323
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5691 - accuracy: 0.7324

In [26]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5848 - accuracy: 0.7187 - 850ms/epoch - 3ms/step
Loss: 0.5847857594490051, Accuracy: 0.7187172174453735

In [27]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimisation1.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(